# yaml-language-server: $schema=https://raw.githubusercontent.com/google/adk-python/refs/heads/main/src/google/adk/agents/config_schemas/AgentConfig.json
name: simple_jira_agent
description: An agent that can read Jira tickets from a CSV file.
instruction: Answer questions about Jira tickets based on the provided CSV file.
author: Gemini
tools:
  - type: adk.python_module
    module: jira_agent.coordination.main
    object: root_agent
